/* File: _cbmlikemodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue May  1 03:55:12 2018
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_cbmlike_error;
static PyObject *_cbmlike_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_cbmlike_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _cbmlike_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _cbmlike_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(sigctp,SIGCTP)(int*,double*,int*,double*,double*);
extern void F_WRAPPEDFUNC(psigc,PSIGC)(double*,double*,int*,double*,double*);
extern void F_WRAPPEDFUNC_US(slml_offset,SLML_OFFSET)(double*,int*,double*,int*,double*);
extern void F_FUNC_US(vslml_offset,VSLML_OFFSET)(int*,int*,double*,int*,double*,double*);
extern void F_WRAPPEDFUNC(slmlike,SLMLIKE)(double*,double*,int*,double*,int*,double*,double*,double*,int*,int*);
extern void F_FUNC(vslmlike,VSLMLIKE)(int*,double*,int*,double*,int*,double*,double*,double*,double*);
extern void F_FUNC(slmliked,SLMLIKED)(double*,int*,double*,int*,double*,double*,double*,double*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** sigctp ***********************************/
static char doc_f2py_rout__cbmlike_sigctp[] = "\
c = sigctp(n_on,t_on,n_off,t_off)\n\nWrapper for ``sigctp``.\
\n\nParameters\n----------\n"
"n_on : input int\n"
"t_on : input float\n"
"n_off : input int\n"
"t_off : input float\n"
"\nReturns\n-------\n"
"c : rank-1 array('d') with bounds (n_on + 1)";
/* extern void F_FUNC(sigctp,SIGCTP)(int*,double*,int*,double*,double*); */
static PyObject *f2py_rout__cbmlike_sigctp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n_on = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int n_off = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  static char *capi_kwlist[] = {"n_on","t_on","n_off","t_off",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:_cbmlike.sigctp",\
    capi_kwlist,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_on */
    f2py_success = int_from_pyobj(&n_on,n_on_capi,"_cbmlike.sigctp() 1st argument (n_on) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.sigctp() 2nd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_off */
    f2py_success = int_from_pyobj(&n_off,n_off_capi,"_cbmlike.sigctp() 3rd argument (n_off) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.sigctp() 4th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable c */
  c_Dims[0]=n_on + 1;
  capi_c_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,Py_None);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting hidden `c' of _cbmlike.sigctp to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n_on,&t_on,&n_off,&t_off,c);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_c_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of n_off*/
  /* End of cleaning variable n_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  } /*if (f2py_success) of n_on*/
  /* End of cleaning variable n_on */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of sigctp *******************************/

/*********************************** psigc ***********************************/
static char doc_f2py_rout__cbmlike_psigc[] = "\
psigc = psigc(s,t_on,c,[n_on])\n\nWrapper for ``psigc``.\
\n\nParameters\n----------\n"
"s : input float\n"
"t_on : input float\n"
"c : input rank-1 array('d') with bounds (n_on + 1)\n"
"\nOther Parameters\n----------------\n"
"n_on : input int, optional\n    Default: (len(c)-1)\n"
"\nReturns\n-------\n"
"psigc : float";
/* extern void F_WRAPPEDFUNC(psigc,PSIGC)(double*,double*,int*,double*,double*); */
static PyObject *f2py_rout__cbmlike_psigc(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double psigc = 0;
  double s = 0;
  PyObject *s_capi = Py_None;
  int n_on = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  static char *capi_kwlist[] = {"s","t_on","c","n_on",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:_cbmlike.psigc",\
    capi_kwlist,&s_capi,&t_on_capi,&c_capi,&n_on_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable s */
    f2py_success = double_from_pyobj(&s,s_capi,"_cbmlike.psigc() 1st argument (s) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.psigc() 2nd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable c */
  ;
  capi_c_intent |= F2PY_INTENT_IN;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 3rd argument `c' of _cbmlike.psigc to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

  /* Processing variable psigc */
  /* Processing variable n_on */
  if (n_on_capi == Py_None) n_on = (len(c)-1); else
    f2py_success = int_from_pyobj(&n_on,n_on_capi,"_cbmlike.psigc() 1st keyword (n_on) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(c)-1)>=n_on,"(len(c)-1)>=n_on","1st keyword n_on","psigc:n_on=%d",n_on) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&psigc,&s,&n_on,&t_on,c);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",psigc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR((len(c)-1)>=n_on)*/
  } /*if (f2py_success) of n_on*/
  /* End of cleaning variable n_on */
  /* End of cleaning variable psigc */
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  } /*if (f2py_success) of s*/
  /* End of cleaning variable s */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of psigc ********************************/

/******************************** slml_offset ********************************/
static char doc_f2py_rout__cbmlike_slml_offset[] = "\
slml_offset = slml_offset(n_on,t_on,n_off,t_off)\n\nWrapper for ``slml_offset``.\
\n\nParameters\n----------\n"
"n_on : input int\n"
"t_on : input float\n"
"n_off : input int\n"
"t_off : input float\n"
"\nReturns\n-------\n"
"slml_offset : float";
/* extern void F_WRAPPEDFUNC_US(slml_offset,SLML_OFFSET)(double*,int*,double*,int*,double*); */
static PyObject *f2py_rout__cbmlike_slml_offset(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double slml_offset = 0;
  int n_on = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int n_off = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  static char *capi_kwlist[] = {"n_on","t_on","n_off","t_off",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:_cbmlike.slml_offset",\
    capi_kwlist,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_on */
    f2py_success = int_from_pyobj(&n_on,n_on_capi,"_cbmlike.slml_offset() 1st argument (n_on) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.slml_offset() 2nd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_off */
    f2py_success = int_from_pyobj(&n_off,n_off_capi,"_cbmlike.slml_offset() 3rd argument (n_off) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.slml_offset() 4th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable slml_offset */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&slml_offset,&n_on,&t_on,&n_off,&t_off);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",slml_offset);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable slml_offset */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of n_off*/
  /* End of cleaning variable n_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  } /*if (f2py_success) of n_on*/
  /* End of cleaning variable n_on */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of slml_offset *****************************/

/******************************** vslml_offset ********************************/
static char doc_f2py_rout__cbmlike_vslml_offset[] = "\
offset = vslml_offset(n_on,t_on,n_off,t_off,[nc])\n\nWrapper for ``vslml_offset``.\
\n\nParameters\n----------\n"
"n_on : input rank-1 array('i') with bounds (nc)\n"
"t_on : input float\n"
"n_off : input rank-1 array('i') with bounds (nc)\n"
"t_off : input float\n"
"\nOther Parameters\n----------------\n"
"nc : input int, optional\n    Default: len(n_on)\n"
"\nReturns\n-------\n"
"offset : rank-1 array('d') with bounds (nc)";
/* extern void F_FUNC_US(vslml_offset,VSLML_OFFSET)(int*,int*,double*,int*,double*,double*); */
static PyObject *f2py_rout__cbmlike_vslml_offset(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nc = 0;
  PyObject *nc_capi = Py_None;
  int *n_on = NULL;
  npy_intp n_on_Dims[1] = {-1};
  const int n_on_Rank = 1;
  PyArrayObject *capi_n_on_tmp = NULL;
  int capi_n_on_intent = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int *n_off = NULL;
  npy_intp n_off_Dims[1] = {-1};
  const int n_off_Rank = 1;
  PyArrayObject *capi_n_off_tmp = NULL;
  int capi_n_off_intent = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  double *offset = NULL;
  npy_intp offset_Dims[1] = {-1};
  const int offset_Rank = 1;
  PyArrayObject *capi_offset_tmp = NULL;
  int capi_offset_intent = 0;
  static char *capi_kwlist[] = {"n_on","t_on","n_off","t_off","nc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:_cbmlike.vslml_offset",\
    capi_kwlist,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi,&nc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_on */
  ;
  capi_n_on_intent |= F2PY_INTENT_IN;
  capi_n_on_tmp = array_from_pyobj(NPY_INT,n_on_Dims,n_on_Rank,capi_n_on_intent,n_on_capi);
  if (capi_n_on_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 1st argument `n_on' of _cbmlike.vslml_offset to C/Fortran array" );
  } else {
    n_on = (int *)(PyArray_DATA(capi_n_on_tmp));

  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.vslml_offset() 2nd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.vslml_offset() 4th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nc */
  if (nc_capi == Py_None) nc = len(n_on); else
    f2py_success = int_from_pyobj(&nc,nc_capi,"_cbmlike.vslml_offset() 1st keyword (nc) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(n_on)>=nc,"len(n_on)>=nc","1st keyword nc","vslml_offset:nc=%d",nc) {
  /* Processing variable n_off */
  n_off_Dims[0]=nc;
  capi_n_off_intent |= F2PY_INTENT_IN;
  capi_n_off_tmp = array_from_pyobj(NPY_INT,n_off_Dims,n_off_Rank,capi_n_off_intent,n_off_capi);
  if (capi_n_off_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 3rd argument `n_off' of _cbmlike.vslml_offset to C/Fortran array" );
  } else {
    n_off = (int *)(PyArray_DATA(capi_n_off_tmp));

  /* Processing variable offset */
  offset_Dims[0]=nc;
  capi_offset_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_offset_tmp = array_from_pyobj(NPY_DOUBLE,offset_Dims,offset_Rank,capi_offset_intent,Py_None);
  if (capi_offset_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting hidden `offset' of _cbmlike.vslml_offset to C/Fortran array" );
  } else {
    offset = (double *)(PyArray_DATA(capi_offset_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nc,n_on,&t_on,n_off,&t_off,offset);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_offset_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_offset_tmp == NULL) ... else of offset*/
  /* End of cleaning variable offset */
  if((PyObject *)capi_n_off_tmp!=n_off_capi) {
    Py_XDECREF(capi_n_off_tmp); }
  }  /*if (capi_n_off_tmp == NULL) ... else of n_off*/
  /* End of cleaning variable n_off */
  } /*CHECKSCALAR(len(n_on)>=nc)*/
  } /*if (f2py_success) of nc*/
  /* End of cleaning variable nc */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  if((PyObject *)capi_n_on_tmp!=n_on_capi) {
    Py_XDECREF(capi_n_on_tmp); }
  }  /*if (capi_n_on_tmp == NULL) ... else of n_on*/
  /* End of cleaning variable n_on */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of vslml_offset ****************************/

/********************************** slmlike **********************************/
static char doc_f2py_rout__cbmlike_slmlike[] = "\
slmlike,nt,ierr = slmlike(s,n_on,t_on,n_off,t_off,offset,cut)\n\nWrapper for ``slmlike``.\
\n\nParameters\n----------\n"
"s : input float\n"
"n_on : input int\n"
"t_on : input float\n"
"n_off : input int\n"
"t_off : input float\n"
"offset : input float\n"
"cut : input float\n"
"\nReturns\n-------\n"
"slmlike : float\n"
"nt : int\n"
"ierr : int";
/* extern void F_WRAPPEDFUNC(slmlike,SLMLIKE)(double*,double*,int*,double*,int*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout__cbmlike_slmlike(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,int*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double slmlike = 0;
  double s = 0;
  PyObject *s_capi = Py_None;
  int n_on = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int n_off = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  double offset = 0;
  PyObject *offset_capi = Py_None;
  double cut = 0;
  PyObject *cut_capi = Py_None;
  int nt = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"s","n_on","t_on","n_off","t_off","offset","cut",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_cbmlike.slmlike",\
    capi_kwlist,&s_capi,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi,&offset_capi,&cut_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable s */
    f2py_success = double_from_pyobj(&s,s_capi,"_cbmlike.slmlike() 1st argument (s) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_on */
    f2py_success = int_from_pyobj(&n_on,n_on_capi,"_cbmlike.slmlike() 2nd argument (n_on) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.slmlike() 3rd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_off */
    f2py_success = int_from_pyobj(&n_off,n_off_capi,"_cbmlike.slmlike() 4th argument (n_off) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.slmlike() 5th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable offset */
    f2py_success = double_from_pyobj(&offset,offset_capi,"_cbmlike.slmlike() 6th argument (offset) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cut */
    f2py_success = double_from_pyobj(&cut,cut_capi,"_cbmlike.slmlike() 7th argument (cut) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nt */
  /* Processing variable ierr */
  /* Processing variable slmlike */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&slmlike,&s,&n_on,&t_on,&n_off,&t_off,&offset,&cut,&nt,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("dii",slmlike,nt,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable slmlike */
  /* End of cleaning variable ierr */
  /* End of cleaning variable nt */
  } /*if (f2py_success) of cut*/
  /* End of cleaning variable cut */
  } /*if (f2py_success) of offset*/
  /* End of cleaning variable offset */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of n_off*/
  /* End of cleaning variable n_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  } /*if (f2py_success) of n_on*/
  /* End of cleaning variable n_on */
  } /*if (f2py_success) of s*/
  /* End of cleaning variable s */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of slmlike *******************************/

/********************************** vslmlike **********************************/
static char doc_f2py_rout__cbmlike_vslmlike[] = "\
slml = vslmlike(s,n_on,t_on,n_off,t_off,offset,cut,[nc])\n\nWrapper for ``vslmlike``.\
\n\nParameters\n----------\n"
"s : input rank-1 array('d') with bounds (nc)\n"
"n_on : input rank-1 array('i') with bounds (nc)\n"
"t_on : input float\n"
"n_off : input rank-1 array('i') with bounds (nc)\n"
"t_off : input float\n"
"offset : input rank-1 array('d') with bounds (nc)\n"
"cut : input float\n"
"\nOther Parameters\n----------------\n"
"nc : input int, optional\n    Default: len(s)\n"
"\nReturns\n-------\n"
"slml : rank-1 array('d') with bounds (nc)";
/* extern void F_FUNC(vslmlike,VSLMLIKE)(int*,double*,int*,double*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout__cbmlike_vslmlike(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,double*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nc = 0;
  PyObject *nc_capi = Py_None;
  double *s = NULL;
  npy_intp s_Dims[1] = {-1};
  const int s_Rank = 1;
  PyArrayObject *capi_s_tmp = NULL;
  int capi_s_intent = 0;
  PyObject *s_capi = Py_None;
  int *n_on = NULL;
  npy_intp n_on_Dims[1] = {-1};
  const int n_on_Rank = 1;
  PyArrayObject *capi_n_on_tmp = NULL;
  int capi_n_on_intent = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int *n_off = NULL;
  npy_intp n_off_Dims[1] = {-1};
  const int n_off_Rank = 1;
  PyArrayObject *capi_n_off_tmp = NULL;
  int capi_n_off_intent = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  double *offset = NULL;
  npy_intp offset_Dims[1] = {-1};
  const int offset_Rank = 1;
  PyArrayObject *capi_offset_tmp = NULL;
  int capi_offset_intent = 0;
  PyObject *offset_capi = Py_None;
  double cut = 0;
  PyObject *cut_capi = Py_None;
  double *slml = NULL;
  npy_intp slml_Dims[1] = {-1};
  const int slml_Rank = 1;
  PyArrayObject *capi_slml_tmp = NULL;
  int capi_slml_intent = 0;
  static char *capi_kwlist[] = {"s","n_on","t_on","n_off","t_off","offset","cut","nc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:_cbmlike.vslmlike",\
    capi_kwlist,&s_capi,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi,&offset_capi,&cut_capi,&nc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable s */
  ;
  capi_s_intent |= F2PY_INTENT_IN;
  capi_s_tmp = array_from_pyobj(NPY_DOUBLE,s_Dims,s_Rank,capi_s_intent,s_capi);
  if (capi_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 1st argument `s' of _cbmlike.vslmlike to C/Fortran array" );
  } else {
    s = (double *)(PyArray_DATA(capi_s_tmp));

  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.vslmlike() 3rd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.vslmlike() 5th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cut */
    f2py_success = double_from_pyobj(&cut,cut_capi,"_cbmlike.vslmlike() 7th argument (cut) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nc */
  if (nc_capi == Py_None) nc = len(s); else
    f2py_success = int_from_pyobj(&nc,nc_capi,"_cbmlike.vslmlike() 1st keyword (nc) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(s)>=nc,"len(s)>=nc","1st keyword nc","vslmlike:nc=%d",nc) {
  /* Processing variable n_on */
  n_on_Dims[0]=nc;
  capi_n_on_intent |= F2PY_INTENT_IN;
  capi_n_on_tmp = array_from_pyobj(NPY_INT,n_on_Dims,n_on_Rank,capi_n_on_intent,n_on_capi);
  if (capi_n_on_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 2nd argument `n_on' of _cbmlike.vslmlike to C/Fortran array" );
  } else {
    n_on = (int *)(PyArray_DATA(capi_n_on_tmp));

  /* Processing variable n_off */
  n_off_Dims[0]=nc;
  capi_n_off_intent |= F2PY_INTENT_IN;
  capi_n_off_tmp = array_from_pyobj(NPY_INT,n_off_Dims,n_off_Rank,capi_n_off_intent,n_off_capi);
  if (capi_n_off_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 4th argument `n_off' of _cbmlike.vslmlike to C/Fortran array" );
  } else {
    n_off = (int *)(PyArray_DATA(capi_n_off_tmp));

  /* Processing variable offset */
  offset_Dims[0]=nc;
  capi_offset_intent |= F2PY_INTENT_IN;
  capi_offset_tmp = array_from_pyobj(NPY_DOUBLE,offset_Dims,offset_Rank,capi_offset_intent,offset_capi);
  if (capi_offset_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting 6th argument `offset' of _cbmlike.vslmlike to C/Fortran array" );
  } else {
    offset = (double *)(PyArray_DATA(capi_offset_tmp));

  /* Processing variable slml */
  slml_Dims[0]=nc;
  capi_slml_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_slml_tmp = array_from_pyobj(NPY_DOUBLE,slml_Dims,slml_Rank,capi_slml_intent,Py_None);
  if (capi_slml_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_cbmlike_error,"failed in converting hidden `slml' of _cbmlike.vslmlike to C/Fortran array" );
  } else {
    slml = (double *)(PyArray_DATA(capi_slml_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nc,s,n_on,&t_on,n_off,&t_off,offset,&cut,slml);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_slml_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_slml_tmp == NULL) ... else of slml*/
  /* End of cleaning variable slml */
  if((PyObject *)capi_offset_tmp!=offset_capi) {
    Py_XDECREF(capi_offset_tmp); }
  }  /*if (capi_offset_tmp == NULL) ... else of offset*/
  /* End of cleaning variable offset */
  if((PyObject *)capi_n_off_tmp!=n_off_capi) {
    Py_XDECREF(capi_n_off_tmp); }
  }  /*if (capi_n_off_tmp == NULL) ... else of n_off*/
  /* End of cleaning variable n_off */
  if((PyObject *)capi_n_on_tmp!=n_on_capi) {
    Py_XDECREF(capi_n_on_tmp); }
  }  /*if (capi_n_on_tmp == NULL) ... else of n_on*/
  /* End of cleaning variable n_on */
  } /*CHECKSCALAR(len(s)>=nc)*/
  } /*if (f2py_success) of nc*/
  /* End of cleaning variable nc */
  } /*if (f2py_success) of cut*/
  /* End of cleaning variable cut */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  if((PyObject *)capi_s_tmp!=s_capi) {
    Py_XDECREF(capi_s_tmp); }
  }  /*if (capi_s_tmp == NULL) ... else of s*/
  /* End of cleaning variable s */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of vslmlike ******************************/

/********************************** slmliked **********************************/
static char doc_f2py_rout__cbmlike_slmliked[] = "\
sll,dsll,nt,ierr = slmliked(s,n_on,t_on,n_off,t_off,offset,cut)\n\nWrapper for ``slmliked``.\
\n\nParameters\n----------\n"
"s : input float\n"
"n_on : input int\n"
"t_on : input float\n"
"n_off : input int\n"
"t_off : input float\n"
"offset : input float\n"
"cut : input float\n"
"\nReturns\n-------\n"
"sll : float\n"
"dsll : float\n"
"nt : int\n"
"ierr : int";
/* extern void F_FUNC(slmliked,SLMLIKED)(double*,int*,double*,int*,double*,double*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout__cbmlike_slmliked(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,int*,double*,double*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double s = 0;
  PyObject *s_capi = Py_None;
  int n_on = 0;
  PyObject *n_on_capi = Py_None;
  double t_on = 0;
  PyObject *t_on_capi = Py_None;
  int n_off = 0;
  PyObject *n_off_capi = Py_None;
  double t_off = 0;
  PyObject *t_off_capi = Py_None;
  double offset = 0;
  PyObject *offset_capi = Py_None;
  double cut = 0;
  PyObject *cut_capi = Py_None;
  double sll = 0;
  double dsll = 0;
  int nt = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"s","n_on","t_on","n_off","t_off","offset","cut",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_cbmlike.slmliked",\
    capi_kwlist,&s_capi,&n_on_capi,&t_on_capi,&n_off_capi,&t_off_capi,&offset_capi,&cut_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable s */
    f2py_success = double_from_pyobj(&s,s_capi,"_cbmlike.slmliked() 1st argument (s) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_on */
    f2py_success = int_from_pyobj(&n_on,n_on_capi,"_cbmlike.slmliked() 2nd argument (n_on) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_on */
    f2py_success = double_from_pyobj(&t_on,t_on_capi,"_cbmlike.slmliked() 3rd argument (t_on) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_off */
    f2py_success = int_from_pyobj(&n_off,n_off_capi,"_cbmlike.slmliked() 4th argument (n_off) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_off */
    f2py_success = double_from_pyobj(&t_off,t_off_capi,"_cbmlike.slmliked() 5th argument (t_off) can't be converted to double");
  if (f2py_success) {
  /* Processing variable offset */
    f2py_success = double_from_pyobj(&offset,offset_capi,"_cbmlike.slmliked() 6th argument (offset) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cut */
    f2py_success = double_from_pyobj(&cut,cut_capi,"_cbmlike.slmliked() 7th argument (cut) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sll */
  /* Processing variable dsll */
  /* Processing variable nt */
  /* Processing variable ierr */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&s,&n_on,&t_on,&n_off,&t_off,&offset,&cut,&sll,&dsll,&nt,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ddii",sll,dsll,nt,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierr */
  /* End of cleaning variable nt */
  /* End of cleaning variable dsll */
  /* End of cleaning variable sll */
  } /*if (f2py_success) of cut*/
  /* End of cleaning variable cut */
  } /*if (f2py_success) of offset*/
  /* End of cleaning variable offset */
  } /*if (f2py_success) of t_off*/
  /* End of cleaning variable t_off */
  } /*if (f2py_success) of n_off*/
  /* End of cleaning variable n_off */
  } /*if (f2py_success) of t_on*/
  /* End of cleaning variable t_on */
  } /*if (f2py_success) of n_on*/
  /* End of cleaning variable n_on */
  } /*if (f2py_success) of s*/
  /* End of cleaning variable s */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of slmliked ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"sigctp",-1,{{-1}},0,(char *)F_FUNC(sigctp,SIGCTP),(f2py_init_func)f2py_rout__cbmlike_sigctp,doc_f2py_rout__cbmlike_sigctp},
  {"psigc",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(psigc,PSIGC),(f2py_init_func)f2py_rout__cbmlike_psigc,doc_f2py_rout__cbmlike_psigc},
  {"slml_offset",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(slml_offset,SLML_OFFSET),(f2py_init_func)f2py_rout__cbmlike_slml_offset,doc_f2py_rout__cbmlike_slml_offset},
  {"vslml_offset",-1,{{-1}},0,(char *)F_FUNC_US(vslml_offset,VSLML_OFFSET),(f2py_init_func)f2py_rout__cbmlike_vslml_offset,doc_f2py_rout__cbmlike_vslml_offset},
  {"slmlike",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(slmlike,SLMLIKE),(f2py_init_func)f2py_rout__cbmlike_slmlike,doc_f2py_rout__cbmlike_slmlike},
  {"vslmlike",-1,{{-1}},0,(char *)F_FUNC(vslmlike,VSLMLIKE),(f2py_init_func)f2py_rout__cbmlike_vslmlike,doc_f2py_rout__cbmlike_vslmlike},
  {"slmliked",-1,{{-1}},0,(char *)F_FUNC(slmliked,SLMLIKED),(f2py_init_func)f2py_rout__cbmlike_slmliked,doc_f2py_rout__cbmlike_slmliked},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_cbmlike",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__cbmlike(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_cbmlike(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _cbmlike_module = PyModule_Create(&moduledef);
#else
  m = _cbmlike_module = Py_InitModule("_cbmlike", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _cbmlike (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_cbmlike' is auto-generated with f2py (version:2).\nFunctions:\n"
"  c = sigctp(n_on,t_on,n_off,t_off)\n"
"  psigc = psigc(s,t_on,c,n_on=(len(c)-1))\n"
"  slml_offset = slml_offset(n_on,t_on,n_off,t_off)\n"
"  offset = vslml_offset(n_on,t_on,n_off,t_off,nc=len(n_on))\n"
"  slmlike,nt,ierr = slmlike(s,n_on,t_on,n_off,t_off,offset,cut)\n"
"  slml = vslmlike(s,n_on,t_on,n_off,t_off,offset,cut,nc=len(s))\n"
"  sll,dsll,nt,ierr = slmliked(s,n_on,t_on,n_off,t_off,offset,cut)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  _cbmlike_error = PyErr_NewException ("_cbmlike.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


    {
      extern double F_FUNC(psigc,PSIGC)(void);
      PyObject* o = PyDict_GetItemString(d,"psigc");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(psigc,PSIGC),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("psigc"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("psigc"));
#endif
    }
    

    {
      extern double F_FUNC_US(slml_offset,SLML_OFFSET)(void);
      PyObject* o = PyDict_GetItemString(d,"slml_offset");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(slml_offset,SLML_OFFSET),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("slml_offset"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("slml_offset"));
#endif
    }
    


    {
      extern double F_FUNC(slmlike,SLMLIKE)(void);
      PyObject* o = PyDict_GetItemString(d,"slmlike");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(slmlike,SLMLIKE),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("slmlike"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("slmlike"));
#endif
    }
    


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_cbmlike");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
